/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const EventSlugIndexLazyImport = createFileRoute('/$eventSlug/')()
const EventSlugReimbursementsLazyImport = createFileRoute(
  '/$eventSlug/reimbursements',
)()
const EventSlugBalancesLazyImport = createFileRoute('/$eventSlug/balances')()

// Create/Update Routes

const EventSlugIndexLazyRoute = EventSlugIndexLazyImport.update({
  path: '/$eventSlug/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$eventSlug/index.lazy').then((d) => d.Route),
)

const EventSlugReimbursementsLazyRoute =
  EventSlugReimbursementsLazyImport.update({
    path: '/$eventSlug/reimbursements',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/$eventSlug/reimbursements.lazy').then((d) => d.Route),
  )

const EventSlugBalancesLazyRoute = EventSlugBalancesLazyImport.update({
  path: '/$eventSlug/balances',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$eventSlug/balances.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$eventSlug/balances': {
      id: '/$eventSlug/balances'
      path: '/$eventSlug/balances'
      fullPath: '/$eventSlug/balances'
      preLoaderRoute: typeof EventSlugBalancesLazyImport
      parentRoute: typeof rootRoute
    }
    '/$eventSlug/reimbursements': {
      id: '/$eventSlug/reimbursements'
      path: '/$eventSlug/reimbursements'
      fullPath: '/$eventSlug/reimbursements'
      preLoaderRoute: typeof EventSlugReimbursementsLazyImport
      parentRoute: typeof rootRoute
    }
    '/$eventSlug/': {
      id: '/$eventSlug/'
      path: '/$eventSlug'
      fullPath: '/$eventSlug'
      preLoaderRoute: typeof EventSlugIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  EventSlugBalancesLazyRoute,
  EventSlugReimbursementsLazyRoute,
  EventSlugIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$eventSlug/balances",
        "/$eventSlug/reimbursements",
        "/$eventSlug/"
      ]
    },
    "/$eventSlug/balances": {
      "filePath": "$eventSlug/balances.lazy.tsx"
    },
    "/$eventSlug/reimbursements": {
      "filePath": "$eventSlug/reimbursements.lazy.tsx"
    },
    "/$eventSlug/": {
      "filePath": "$eventSlug/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
