/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ReimbursementsLazyImport = createFileRoute('/reimbursements')()
const BalancesLazyImport = createFileRoute('/balances')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ReimbursementsLazyRoute = ReimbursementsLazyImport.update({
  path: '/reimbursements',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reimbursements.lazy').then((d) => d.Route),
)

const BalancesLazyRoute = BalancesLazyImport.update({
  path: '/balances',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/balances.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/balances': {
      id: '/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof BalancesLazyImport
      parentRoute: typeof rootRoute
    }
    '/reimbursements': {
      id: '/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof ReimbursementsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  BalancesLazyRoute,
  ReimbursementsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/balances",
        "/reimbursements"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/balances": {
      "filePath": "balances.lazy.tsx"
    },
    "/reimbursements": {
      "filePath": "reimbursements.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
